FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

RUN pip install --upgrade pip

COPY ./geitje_service/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ./geitje_service /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]